//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string DeliveryMan { get; set; }
        public string Status { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
